spring:
  rabbitmq:
    host: 47.107.134.157
    port: 5672
    username: admin
    password: admin
    publisher-confirms: true  #  消息发送到交换机确认机制,是否确认回调
    publisher-returns: true
  devtools:
    restart:
      enabled: false
server:
  port: 8081
